# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'QT_Main.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainPage(object):
    def setupUi(self, MainPage):
        MainPage.setObjectName("MainPage")
        MainPage.resize(1900, 1080)
        font = QtGui.QFont()
        font.setPointSize(15)
        MainPage.setFont(font)
        MainPage.setStyleSheet("background-color: rgb(10, 5, 27);\n"
"color: white;")
        self.centralwidget = QtWidgets.QWidget(MainPage)
        self.centralwidget.setObjectName("centralwidget")
        self.Main_frame = QtWidgets.QFrame(self.centralwidget)
        self.Main_frame.setGeometry(QtCore.QRect(0, 50, 1890, 980))
        self.Main_frame.setStyleSheet("background-color: rgb(10, 5, 27);\n"
"\n"
"\n"
"")
        self.Main_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Main_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Main_frame.setObjectName("Main_frame")
        self.Toolbar = QtWidgets.QTabWidget(self.Main_frame)
        self.Toolbar.setGeometry(QtCore.QRect(10, 20, 390, 950))
        self.Toolbar.setStyleSheet("background-color: rgb(11, 14, 30);\n"
"color: white;\n"
"border-radius: 1px;\n"
"\n"
"\n"
"")
        self.Toolbar.setObjectName("Toolbar")
        self.tab_model = QtWidgets.QWidget()
        self.tab_model.setStyleSheet("background-color: rgb(11, 14, 30);\n"
"color: white;\n"
"border-radius: 10px;\n"
"\n"
"")
        self.tab_model.setObjectName("tab_model")
        self.widget_tab_model = QtWidgets.QWidget(self.tab_model)
        self.widget_tab_model.setGeometry(QtCore.QRect(0, 0, 390, 910))
        self.widget_tab_model.setStyleSheet("background-color: rgb(11, 14, 30);\n"
"color: white;\n"
"border-radius: 1px;\n"
"\n"
"")
        self.widget_tab_model.setObjectName("widget_tab_model")
        self.pushButton_4 = QtWidgets.QPushButton(self.widget_tab_model)
        self.pushButton_4.setGeometry(QtCore.QRect(290, 10, 89, 25))
        self.pushButton_4.setStyleSheet("background-color: rgb(17, 17, 27);\n"
"color: white;")
        self.pushButton_4.setObjectName("pushButton_4")
        self.checkBox = QtWidgets.QCheckBox(self.widget_tab_model)
        self.checkBox.setGeometry(QtCore.QRect(0, 50, 200, 30))
        self.checkBox.setStyleSheet("QCheckBox{\n"
"    background-color: rgb(11, 14, 30);\n"
"    border-radius: 15px;\n"
"font: 75 15pt \"MS Shell Dlg 2\";\n"
"}\n"
"\n"
"QCheckBox::indicator {\n"
"    \n"
"    border-radius: 5px; /* Đặt độ cong cho ô tích */\n"
"    width: 20px; /* Đặt chiều rộng của ô tích */\n"
"    height: 20px; /* Đặt chiều cao của ô tích */\n"
"    border: 2px solid rgb(0, 0, 0);\n"
"    position: absolute; /* Sử dụng position để định vị */\n"
"    top: 0; /* Di chuyển indicator lên phía trên */\n"
"left:10;\n"
"}\n"
"\n"
"QCheckBox::indicator:unchecked{\n"
"    background-color: rgb(255, 255, 255);\n"
"\n"
"}\n"
"QCheckBox::indicator:checked{\n"
"    \n"
"    \n"
"background-color: rgb(106, 255, 153);\n"
"\n"
"}\n"
"\n"
"\n"
"")
        self.checkBox.setObjectName("checkBox")
        self.checkBox_2 = QtWidgets.QCheckBox(self.widget_tab_model)
        self.checkBox_2.setGeometry(QtCore.QRect(20, 90, 200, 30))
        self.checkBox_2.setStyleSheet("QCheckBox{\n"
"    background-color: rgb(11, 14, 30);\n"
"    border-radius: 15px;\n"
"font: 75 15pt \"MS Shell Dlg 2\";\n"
"}\n"
"\n"
"QCheckBox::indicator {\n"
"    \n"
"    border-radius: 5px; /* Đặt độ cong cho ô tích */\n"
"    width: 20px; /* Đặt chiều rộng của ô tích */\n"
"    height: 20px; /* Đặt chiều cao của ô tích */\n"
"    border: 2px solid rgb(0, 0, 0);\n"
"    position: absolute; /* Sử dụng position để định vị */\n"
"    top: 0; /* Di chuyển indicator lên phía trên */\n"
"left:10;\n"
"}\n"
"\n"
"QCheckBox::indicator:unchecked{\n"
"    background-color: rgb(255, 255, 255);\n"
"\n"
"}\n"
"QCheckBox::indicator:checked{\n"
"    \n"
"    \n"
"background-color: rgb(106, 255, 153);\n"
"\n"
"}\n"
"\n"
"\n"
"")
        self.checkBox_2.setObjectName("checkBox_2")
        self.checkBox_3 = QtWidgets.QCheckBox(self.widget_tab_model)
        self.checkBox_3.setGeometry(QtCore.QRect(20, 120, 201, 31))
        self.checkBox_3.setStyleSheet("QCheckBox{\n"
"    background-color: rgb(11, 14, 30);\n"
"    border-radius: 15px;\n"
"font: 75 15pt \"MS Shell Dlg 2\";\n"
"}\n"
"\n"
"QCheckBox::indicator {\n"
"    \n"
"    border-radius: 5px; /* Đặt độ cong cho ô tích */\n"
"    width: 20px; /* Đặt chiều rộng của ô tích */\n"
"    height: 20px; /* Đặt chiều cao của ô tích */\n"
"    border: 2px solid rgb(0, 0, 0);\n"
"    position: absolute; /* Sử dụng position để định vị */\n"
"    top: 0; /* Di chuyển indicator lên phía trên */\n"
"left:10;\n"
"}\n"
"\n"
"QCheckBox::indicator:unchecked{\n"
"    background-color: rgb(255, 255, 255);\n"
"\n"
"}\n"
"QCheckBox::indicator:checked{\n"
"    \n"
"    \n"
"background-color: rgb(106, 255, 153);\n"
"\n"
"}\n"
"\n"
"\n"
"")
        self.checkBox_3.setObjectName("checkBox_3")
        self.checkBox_4 = QtWidgets.QCheckBox(self.widget_tab_model)
        self.checkBox_4.setGeometry(QtCore.QRect(20, 150, 201, 31))
        self.checkBox_4.setStyleSheet("QCheckBox{\n"
"    background-color: rgb(11, 14, 30);\n"
"    border-radius: 15px;\n"
"font: 75 15pt \"MS Shell Dlg 2\";\n"
"}\n"
"\n"
"QCheckBox::indicator {\n"
"    \n"
"    border-radius: 5px; /* Đặt độ cong cho ô tích */\n"
"    width: 20px; /* Đặt chiều rộng của ô tích */\n"
"    height: 20px; /* Đặt chiều cao của ô tích */\n"
"    border: 2px solid rgb(0, 0, 0);\n"
"    position: absolute; /* Sử dụng position để định vị */\n"
"    top: 0; /* Di chuyển indicator lên phía trên */\n"
"left:10;\n"
"}\n"
"\n"
"QCheckBox::indicator:unchecked{\n"
"    background-color: rgb(255, 255, 255);\n"
"\n"
"}\n"
"QCheckBox::indicator:checked{\n"
"    \n"
"    \n"
"background-color: rgb(106, 255, 153);\n"
"\n"
"}\n"
"\n"
"\n"
"")
        self.checkBox_4.setObjectName("checkBox_4")
        self.checkBox_5 = QtWidgets.QCheckBox(self.widget_tab_model)
        self.checkBox_5.setGeometry(QtCore.QRect(20, 180, 201, 31))
        self.checkBox_5.setStyleSheet("QCheckBox{\n"
"    background-color: rgb(11, 14, 30);\n"
"    border-radius: 15px;\n"
"font: 75 15pt \"MS Shell Dlg 2\";\n"
"}\n"
"\n"
"QCheckBox::indicator {\n"
"    \n"
"    border-radius: 5px; /* Đặt độ cong cho ô tích */\n"
"    width: 20px; /* Đặt chiều rộng của ô tích */\n"
"    height: 20px; /* Đặt chiều cao của ô tích */\n"
"    border: 2px solid rgb(0, 0, 0);\n"
"    position: absolute; /* Sử dụng position để định vị */\n"
"    top: 0; /* Di chuyển indicator lên phía trên */\n"
"left:10;\n"
"}\n"
"\n"
"QCheckBox::indicator:unchecked{\n"
"    background-color: rgb(255, 255, 255);\n"
"\n"
"}\n"
"QCheckBox::indicator:checked{\n"
"    \n"
"    \n"
"background-color: rgb(106, 255, 153);\n"
"\n"
"}\n"
"\n"
"\n"
"")
        self.checkBox_5.setObjectName("checkBox_5")
        self.Toolbar.addTab(self.tab_model, "")
        self.tab_Machining = QtWidgets.QWidget()
        self.tab_Machining.setObjectName("tab_Machining")
        self.widget_tab_Machining = QtWidgets.QWidget(self.tab_Machining)
        self.widget_tab_Machining.setGeometry(QtCore.QRect(0, 0, 391, 911))
        self.widget_tab_Machining.setStyleSheet("background-color: rgb(11, 14, 30);\n"
"color: white;\n"
"\n"
"border-radius: 10px;")
        self.widget_tab_Machining.setObjectName("widget_tab_Machining")
        self.btn_settings_mc = QtWidgets.QPushButton(self.widget_tab_Machining)
        self.btn_settings_mc.setGeometry(QtCore.QRect(10, 10, 89, 25))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.btn_settings_mc.setFont(font)
        self.btn_settings_mc.setStyleSheet("\n"
"QPushButton#btn_settings_mc{\n"
"    background-color: rgb(17, 17, 27);\n"
"    color: white;\n"
"\n"
"}\n"
"QPushButton#btn_settings_mc:pressed{\n"
" background-color:rgba( 0, 135, 255);\n"
"}")
        self.btn_settings_mc.setObjectName("btn_settings_mc")
        self.widget_arm = QtWidgets.QWidget(self.widget_tab_Machining)
        self.widget_arm.setGeometry(QtCore.QRect(10, 60, 361, 481))
        self.widget_arm.setStyleSheet("background-color: rgb(17, 17, 42)")
        self.widget_arm.setObjectName("widget_arm")
        self.label = QtWidgets.QLabel(self.widget_arm)
        self.label.setGeometry(QtCore.QRect(90, 0, 181, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.widget_arm)
        self.label_2.setGeometry(QtCore.QRect(10, 60, 85, 20))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.widget_arm)
        self.label_3.setGeometry(QtCore.QRect(10, 120, 90, 20))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.widget_arm)
        self.label_4.setGeometry(QtCore.QRect(10, 140, 90, 20))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.widget_arm)
        self.label_5.setGeometry(QtCore.QRect(10, 160, 90, 20))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.widget_arm)
        self.label_6.setGeometry(QtCore.QRect(10, 180, 90, 20))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.widget_arm)
        self.label_7.setGeometry(QtCore.QRect(10, 200, 90, 20))
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.widget_arm)
        self.label_8.setGeometry(QtCore.QRect(10, 220, 90, 20))
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.widget_arm)
        self.label_9.setGeometry(QtCore.QRect(10, 240, 90, 20))
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.widget_arm)
        self.label_10.setGeometry(QtCore.QRect(10, 80, 85, 20))
        self.label_10.setObjectName("label_10")
        self.label_13 = QtWidgets.QLabel(self.widget_arm)
        self.label_13.setGeometry(QtCore.QRect(10, 40, 110, 20))
        self.label_13.setObjectName("label_13")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.widget_arm)
        self.lineEdit_2.setGeometry(QtCore.QRect(120, 140, 60, 20))
        self.lineEdit_2.setAutoFillBackground(False)
        self.lineEdit_2.setStyleSheet("background-color: rgb(17, 17, 27);\n"
"color: white;")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.widget_arm)
        self.lineEdit_3.setGeometry(QtCore.QRect(120, 160, 60, 20))
        self.lineEdit_3.setAutoFillBackground(False)
        self.lineEdit_3.setStyleSheet("background-color: rgb(17, 17, 27);\n"
"color: white;")
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.widget_arm)
        self.lineEdit_4.setGeometry(QtCore.QRect(120, 180, 60, 20))
        self.lineEdit_4.setAutoFillBackground(False)
        self.lineEdit_4.setStyleSheet("background-color: rgb(17, 17, 27);\n"
"color: white;")
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.lineEdit_5 = QtWidgets.QLineEdit(self.widget_arm)
        self.lineEdit_5.setGeometry(QtCore.QRect(120, 120, 60, 20))
        self.lineEdit_5.setAutoFillBackground(False)
        self.lineEdit_5.setStyleSheet("background-color: rgb(17, 17, 27);\n"
"color: white;")
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.lineEdit_6 = QtWidgets.QLineEdit(self.widget_arm)
        self.lineEdit_6.setGeometry(QtCore.QRect(120, 40, 60, 20))
        self.lineEdit_6.setAutoFillBackground(False)
        self.lineEdit_6.setStyleSheet("background-color: rgb(17, 17, 27);\n"
"color: white;")
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.lineEdit_7 = QtWidgets.QLineEdit(self.widget_arm)
        self.lineEdit_7.setGeometry(QtCore.QRect(120, 60, 60, 20))
        self.lineEdit_7.setAutoFillBackground(False)
        self.lineEdit_7.setStyleSheet("background-color: rgb(17, 17, 27);\n"
"color: white;")
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.lineEdit_8 = QtWidgets.QLineEdit(self.widget_arm)
        self.lineEdit_8.setGeometry(QtCore.QRect(120, 80, 60, 20))
        self.lineEdit_8.setAutoFillBackground(False)
        self.lineEdit_8.setStyleSheet("background-color: rgb(17, 17, 27);\n"
"color: white;")
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.lineEdit_9 = QtWidgets.QLineEdit(self.widget_arm)
        self.lineEdit_9.setGeometry(QtCore.QRect(120, 200, 60, 20))
        self.lineEdit_9.setAutoFillBackground(False)
        self.lineEdit_9.setStyleSheet("background-color: rgb(17, 17, 27);\n"
"color: white;")
        self.lineEdit_9.setObjectName("lineEdit_9")
        self.lineEdit_10 = QtWidgets.QLineEdit(self.widget_arm)
        self.lineEdit_10.setGeometry(QtCore.QRect(120, 220, 60, 20))
        self.lineEdit_10.setAutoFillBackground(False)
        self.lineEdit_10.setStyleSheet("background-color: rgb(17, 17, 27);\n"
"color: white;")
        self.lineEdit_10.setObjectName("lineEdit_10")
        self.lineEdit_11 = QtWidgets.QLineEdit(self.widget_arm)
        self.lineEdit_11.setGeometry(QtCore.QRect(120, 240, 60, 20))
        self.lineEdit_11.setAutoFillBackground(False)
        self.lineEdit_11.setStyleSheet("background-color: rgb(17, 17, 27);\n"
"color: white;")
        self.lineEdit_11.setObjectName("lineEdit_11")
        self.Toolbar.addTab(self.tab_Machining, "")
        self.tab_Simulation = QtWidgets.QWidget()
        self.tab_Simulation.setObjectName("tab_Simulation")
        self.widget_tab_Simulation = QtWidgets.QWidget(self.tab_Simulation)
        self.widget_tab_Simulation.setGeometry(QtCore.QRect(0, 0, 391, 911))
        self.widget_tab_Simulation.setStyleSheet("background-color: rgb(11, 14, 30);\n"
"color: white;\n"
"border-radius: 10px;\n"
"\n"
"")
        self.widget_tab_Simulation.setObjectName("widget_tab_Simulation")
        self.btn_play_simulation = QtWidgets.QPushButton(self.widget_tab_Simulation)
        self.btn_play_simulation.setGeometry(QtCore.QRect(280, 20, 31, 30))
        self.btn_play_simulation.setStyleSheet("QPushButton#btn_play_simulation{\n"
"    background-color: rgb(17, 17, 27);\n"
"    color: white;\n"
"\n"
"}\n"
"QPushButton#btn_play_simulation:pressed{\n"
" background-color:rgba( 0, 135, 255);\n"
"}")
        self.btn_play_simulation.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../Icon/icon_play.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_play_simulation.setIcon(icon)
        self.btn_play_simulation.setIconSize(QtCore.QSize(30, 30))
        self.btn_play_simulation.setObjectName("btn_play_simulation")
        self.pushButton_2 = QtWidgets.QPushButton(self.widget_tab_Simulation)
        self.pushButton_2.setGeometry(QtCore.QRect(110, 20, 60, 30))
        self.pushButton_2.setStyleSheet("background-color: rgb(17, 17, 27);\n"
"color: white;")
        self.pushButton_2.setObjectName("pushButton_2")
        self.widget = QtWidgets.QWidget(self.widget_tab_Simulation)
        self.widget.setGeometry(QtCore.QRect(10, 70, 361, 551))
        self.widget.setStyleSheet("background-color: rgb(17, 17, 42)")
        self.widget.setObjectName("widget")
        self.label_11 = QtWidgets.QLabel(self.widget)
        self.label_11.setGeometry(QtCore.QRect(100, 10, 161, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_11.setFont(font)
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName("label_11")
        self.pushButton_9 = QtWidgets.QPushButton(self.widget_tab_Simulation)
        self.pushButton_9.setGeometry(QtCore.QRect(10, 20, 90, 30))
        self.pushButton_9.setStyleSheet("background-color: rgb(17, 17, 27);\n"
"color: white;\n"
"boder-radius : 10px;")
        self.pushButton_9.setObjectName("pushButton_9")
        self.pushButton_5 = QtWidgets.QPushButton(self.widget_tab_Simulation)
        self.pushButton_5.setGeometry(QtCore.QRect(320, 20, 31, 30))
        self.pushButton_5.setStyleSheet("")
        self.pushButton_5.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("../Icon/forward-icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_5.setIcon(icon1)
        self.pushButton_5.setIconSize(QtCore.QSize(30, 30))
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_10 = QtWidgets.QPushButton(self.widget_tab_Simulation)
        self.pushButton_10.setGeometry(QtCore.QRect(240, 20, 31, 30))
        self.pushButton_10.setStyleSheet("")
        self.pushButton_10.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("../Icon/backward-icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_10.setIcon(icon2)
        self.pushButton_10.setIconSize(QtCore.QSize(30, 30))
        self.pushButton_10.setObjectName("pushButton_10")
        self.Toolbar.addTab(self.tab_Simulation, "")
        self.tab_Excute = QtWidgets.QWidget()
        self.tab_Excute.setStyleSheet("background-color: rgb(11, 14, 30);\n"
"color: white;\n"
"\n"
"")
        self.tab_Excute.setObjectName("tab_Excute")
        self.pushButton_3 = QtWidgets.QPushButton(self.tab_Excute)
        self.pushButton_3.setGeometry(QtCore.QRect(10, 50, 60, 30))
        self.pushButton_3.setStyleSheet("background-color: rgb(17, 17, 27);\n"
"color: white;")
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_6 = QtWidgets.QPushButton(self.tab_Excute)
        self.pushButton_6.setGeometry(QtCore.QRect(10, 10, 71, 30))
        self.pushButton_6.setStyleSheet("background-color: rgb(17, 17, 27);\n"
"color: white;")
        self.pushButton_6.setObjectName("pushButton_6")
        self.Toolbar.addTab(self.tab_Excute, "")
        self.rvizContainer = QtWidgets.QWidget(self.Main_frame)
        self.rvizContainer.setGeometry(QtCore.QRect(420, 50, 1391, 921))
        self.rvizContainer.setStyleSheet("background-color: rgb(11, 14, 30);\n"
"border-radius: 10px;")
        self.rvizContainer.setObjectName("rvizContainer")
        self.rvizContainer_2 = QtWidgets.QWidget(self.Main_frame)
        self.rvizContainer_2.setGeometry(QtCore.QRect(1830, 50, 50, 921))
        self.rvizContainer_2.setStyleSheet("background-color: rgb(11, 14, 30);\n"
"border-radius: 10px;")
        self.rvizContainer_2.setObjectName("rvizContainer_2")
        self.label_name_file = QtWidgets.QLabel(self.centralwidget)
        self.label_name_file.setGeometry(QtCore.QRect(950, -10, 231, 51))
        font = QtGui.QFont()
        font.setPointSize(25)
        self.label_name_file.setFont(font)
        self.label_name_file.setAlignment(QtCore.Qt.AlignCenter)
        self.label_name_file.setObjectName("label_name_file")
        MainPage.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainPage)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1900, 22))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuEdit = QtWidgets.QMenu(self.menubar)
        self.menuEdit.setObjectName("menuEdit")
        self.menuView = QtWidgets.QMenu(self.menubar)
        self.menuView.setObjectName("menuView")
        self.menuSettings = QtWidgets.QMenu(self.menubar)
        self.menuSettings.setObjectName("menuSettings")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        MainPage.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainPage)
        self.statusbar.setObjectName("statusbar")
        MainPage.setStatusBar(self.statusbar)
        self.actionNew_FIle = QtWidgets.QAction(MainPage)
        self.actionNew_FIle.setObjectName("actionNew_FIle")
        self.actionOpen_File = QtWidgets.QAction(MainPage)
        self.actionOpen_File.setObjectName("actionOpen_File")
        self.actionSave = QtWidgets.QAction(MainPage)
        self.actionSave.setObjectName("actionSave")
        self.actionSave_as = QtWidgets.QAction(MainPage)
        self.actionSave_as.setObjectName("actionSave_as")
        self.actionQuit = QtWidgets.QAction(MainPage)
        self.actionQuit.setObjectName("actionQuit")
        self.actionImport_File = QtWidgets.QAction(MainPage)
        self.actionImport_File.setObjectName("actionImport_File")
        self.actionExport = QtWidgets.QAction(MainPage)
        self.actionExport.setObjectName("actionExport")
        self.actionCovert = QtWidgets.QAction(MainPage)
        self.actionCovert.setObjectName("actionCovert")
        self.menuFile.addAction(self.actionNew_FIle)
        self.menuFile.addAction(self.actionOpen_File)
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addAction(self.actionSave_as)
        self.menuFile.addAction(self.actionImport_File)
        self.menuFile.addAction(self.actionExport)
        self.menuFile.addAction(self.actionQuit)
        self.menuEdit.addAction(self.actionCovert)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())
        self.menubar.addAction(self.menuView.menuAction())
        self.menubar.addAction(self.menuSettings.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainPage)
        self.Toolbar.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(MainPage)

    def retranslateUi(self, MainPage):
        _translate = QtCore.QCoreApplication.translate
        MainPage.setWindowTitle(_translate("MainPage", "MainWindow"))
        self.pushButton_4.setText(_translate("MainPage", "Import"))
        self.checkBox.setText(_translate("MainPage", "Full Model"))
        self.checkBox_2.setText(_translate("MainPage", "Part"))
        self.checkBox_3.setText(_translate("MainPage", "WorkPiece"))
        self.checkBox_4.setText(_translate("MainPage", "Fixtures"))
        self.checkBox_5.setText(_translate("MainPage", "Restrictions"))
        self.Toolbar.setTabText(self.Toolbar.indexOf(self.tab_model), _translate("MainPage", "Model"))
        self.btn_settings_mc.setText(_translate("MainPage", "Settings"))
        self.label.setText(_translate("MainPage", "Thông số "))
        self.label_2.setText(_translate("MainPage", "Tốc độ dao :"))
        self.label_3.setText(_translate("MainPage", "Vị trí khớp 0 :"))
        self.label_4.setText(_translate("MainPage", "Vị trí khớp 1 :"))
        self.label_5.setText(_translate("MainPage", "Vị trí khớp 2:"))
        self.label_6.setText(_translate("MainPage", "Vị trí khớp 3:"))
        self.label_7.setText(_translate("MainPage", "Vị trí khớp 4:"))
        self.label_8.setText(_translate("MainPage", "Vị trí khớp 5:"))
        self.label_9.setText(_translate("MainPage", "Vị trí khớp 6:"))
        self.label_10.setText(_translate("MainPage", "Vị trí  TCP :"))
        self.label_13.setText(_translate("MainPage", "Trạng thái dao :"))
        self.lineEdit_2.setText(_translate("MainPage", "-000.00"))
        self.lineEdit_3.setText(_translate("MainPage", "-000.00"))
        self.lineEdit_4.setText(_translate("MainPage", "-000.00"))
        self.lineEdit_5.setText(_translate("MainPage", "-000.00"))
        self.lineEdit_6.setText(_translate("MainPage", "000000"))
        self.lineEdit_7.setText(_translate("MainPage", "000000"))
        self.lineEdit_8.setText(_translate("MainPage", "000000"))
        self.lineEdit_9.setText(_translate("MainPage", "-000.00"))
        self.lineEdit_10.setText(_translate("MainPage", "-000.00"))
        self.lineEdit_11.setText(_translate("MainPage", "-000.00"))
        self.Toolbar.setTabText(self.Toolbar.indexOf(self.tab_Machining), _translate("MainPage", "Machining"))
        self.pushButton_2.setText(_translate("MainPage", "Plan"))
        self.label_11.setText(_translate("MainPage", "Đường chạy dao"))
        self.pushButton_9.setText(_translate("MainPage", "ToolPath"))
        self.Toolbar.setTabText(self.Toolbar.indexOf(self.tab_Simulation), _translate("MainPage", "Simulation"))
        self.pushButton_3.setText(_translate("MainPage", "Excute"))
        self.pushButton_6.setText(_translate("MainPage", "Connect"))
        self.Toolbar.setTabText(self.Toolbar.indexOf(self.tab_Excute), _translate("MainPage", "Excute"))
        self.label_name_file.setText(_translate("MainPage", "ROBOT ARM"))
        self.menuFile.setTitle(_translate("MainPage", "File"))
        self.menuEdit.setTitle(_translate("MainPage", "Edit"))
        self.menuView.setTitle(_translate("MainPage", "View"))
        self.menuSettings.setTitle(_translate("MainPage", "Settings"))
        self.menuHelp.setTitle(_translate("MainPage", "Help"))
        self.actionNew_FIle.setText(_translate("MainPage", "New File"))
        self.actionOpen_File.setText(_translate("MainPage", "Open File"))
        self.actionSave.setText(_translate("MainPage", "Save"))
        self.actionSave_as.setText(_translate("MainPage", "Save as"))
        self.actionQuit.setText(_translate("MainPage", "Quit"))
        self.actionImport_File.setText(_translate("MainPage", "Import"))
        self.actionExport.setText(_translate("MainPage", "Export"))
        self.actionCovert.setText(_translate("MainPage", "Covert"))
